apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-hello-world
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: maven-hello-world
  template:
    metadata:
      labels:
        app: maven-hello-world
    spec:
      containers:
      - name: app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8080