apiVersion: v1
kind: Service
metadata:
  name: maven-hello-world
spec:
  selector:
    app: maven-hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: {{ .Values.service.type }}