FROM openjdk:11-jre-slim
ARG VERSION
WORKDIR /app
RUN groupadd -r appgroup && useradd -r -g appgroup appuser
RUN chown -R appuser:appgroup /app
USER appuser
EXPOSE 8080
COPY myapp-${VERSION}.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]