FROM openjdk:11-jre-slim
WORKDIR /app
RUN groupadd -r appgroup && useradd -r -g appgroup appuser
RUN chown -R appuser:appgroup /app
USER appuser
EXPOSE 8080
COPY app.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]